<?php

/**
 * Prepares variables for `block.html.twig`.
 */
function miteshmap_preprocess_block(&$variables) {
  switch ($variables['elements']['#plugin_id']) {
    case 'system_branding_block':
      $variables['content']['site_logo']['#width'] = '100px';
      $variables['content']['site_logo']['#attributes'] = ['class' => ['rounded-circle']];
      $variables['elements']['content'] = $variables['content'];
      break;
  }
}
